### ISSUE TITLE
Initialize Beda EMR submodule

### ISSUE THREAD

**Issue by rrabreu2425** [beda-software/emr-template#1]
![Screenshot 2024-10-21 084240](https://github.com/user-attachments/assets/cb15561d-a211-4b5b-ba5e-907140286ddc)
Good morning, I'm having trouble initializing the Beda EMR modules for the template you created. If you could help me I would be very grateful. Best regards, @vesnushka

**Comment by ir4y** [comment]
Hi @rrabreu2425 
You need to setup ssh access to GitHub, or you can manually change submodule url to be https instead of ssh.

**Comment by rrabreu2425** [comment]
Ok perfect, I will check that when I’m stay at home, thank very much
